name: mobx_translator
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  mobx: ^1.0.2
  flutter_mobx: ^1.0.1
  translator: ^0.1.4

dev_dependencies:
  mobx_codegen:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true